### ISSUE TITLE
Error: Pyperclip could not find a copy/paste mechanism for your system.

### ISSUE THREAD

**Issue by donatid** [RaihanStark/instaliveweb#6]
Hi,
I found the following problem in my server:
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

Error log:

> Login to Instagram Server
- Login Success
> Creating Broadcast
[2020-07-29 19:22:15,309] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/home/instaliveweb/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/instaliveweb/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/instaliveweb/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/instaliveweb/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/instaliveweb/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/instaliveweb/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/instaliveweb/app/base/views.py", line 57, in login_handle
    live.create_broadcast()
  File "/home/instaliveweb/env/lib/python3.8/site-packages/InstaLiveCLI/InstaLiveCLI.py", line 617, in create_broadcast
    pyperclip.copy(self.stream_key)
  File "/home/instaliveweb/env/lib/python3.8/site-packages/pyperclip/__init__.py", line 618, in lazy_load_stub_copy
    return copy(text)
  File "/home/instaliveweb/env/lib/python3.8/site-packages/pyperclip/__init__.py", line 303, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error

Do you have any suggestions?

Thank you

**Comment by donatid** [comment]
It's a problem at instalivecli, not web version.
